const list = [
  {
    id: 1,
    title: "Typing Website",
    about: "This is Multipage Website and it contain multiple practice section",
    src: "./images/1.png",
    live: "https://keytype.herokuapp.com/",
    github: "https://github.com/Ankit8969/Typing-Website-with-backend",
  },
  {
    id: 2,
    title: "Google Gmail",
    about: "This Gmail I created using React.js",
    src: "./images/2.png",
    live: "https://gmail-react-ankit.netlify.app/",
    github: "https://github.com/Ankit8969/Gmail-clone-react",
  },
  {
    id: 3,
    title: "Link Storage System",
    about: "This is Link Storage Web-app you can store the link for long time.",
    src: "./images/3.png",
    live: "https://ankit-links-storage.netlify.app/",
    github: "https://github.com/Ankit8969/React-Link-Storage",
  },
  {
    id: 4,
    title: "Html Css Editor",
    about:
      "It works like CodePen and I also used local storage for storing the last code",
    src: "./images/4.png",
    live: "https://html-css-editor.netlify.app/",
    github: "https://github.com/Ankit8969/React-Link-Storage",
  },
  {
    id: 5,
    title: "CockTail Database",
    about:
      "In this project I used external api for geting the cocktail details",
    src: "./images/5.png",
    live: "https://cocktail-ankit.netlify.app/",
    github: "https://github.com/Ankit8969/Cocktail-Project",
  },
  {
    id: 6,
    title: "Shoping Card",
    about: "This is single Page shoping cart website using Html, Css and Js",
    src: "./images/6.png",
    live: "https://ankit8969.github.io/Shoping-cart/",
    github: "https://github.com/Ankit8969/Shoping-cart",
  },
  {
    id: 7,
    title: "Weather Web-app",
    about:
      "In this project I used and external api for getting the weather's data",
    src: "./images/7.png",
    live: "https://weather-ankitkumar.herokuapp.com/",
    github: "https://github.com/Ankit8969/weather-app",
  },
  {
    id: 8,
    title: "WebSite Template",
    about: "This is a single page website template",
    src: "./images/8.png",
    live: "https://ankit8969.github.io/coursify-template/",
    github: "https://github.com/Ankit8969/coursify-template",
  },
  {
    id: 9,
    title: "WebSite Template",
    about: "This is a single page website template",
    src: "./images/9.png",
    live: "https://ankit8969.github.io/Hotel-Booking/",
    github: "https://github.com/Ankit8969/Hotel-Booking/settings/pages",
  },
  {
    id: 10,
    title: "WebSite Template",
    about: "This is a single page website template",
    src: "./images/10.png",
    live: "https://ankit8969.github.io/ATIN-dog-project/",
    github: "https://github.com/Ankit8969/ATIN-dog-project",
  },
  {
    id: 11,
    title: "WebSite Template",
    about: "This is a single page website template",
    src: "./images/11.png",
    live: "https://ankit8969.github.io/ankit-about/",
    github: "https://github.com/Ankit8969/ankit-about",
  },
  {
    id: 12,
    title: "WebSite Template",
    about: "This is a single page website template",
    src: "./images/12.png",
    live: "https://ankit8969.github.io/Make-Friend-List/",
    github: "https://github.com/Ankit8969",
  },
];

export default list;
